heat_template_version: 2015-04-30

description: MariaDB Service

parameters:
  key_name:
    type: string
    label: Key Name
    description: Name of key-pair to be used for compute instance
    default: cloud_app_key
  image_id:
    type: string
    label: Image ID
    description: Image to be used for compute instance
    default: Ubuntu 16.04 "Xenial Xerus"
  instance_type:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used
    default: v2.m2.d5
  network:
    type: string
    label: Network
  sg:
    type: string
    label: Security group
    default: db
  db_root_password:
    type: string
    label: MariaDB root password
    default: plusbeton
  db_name:
    type: string
    label: MariaDB databse name
    default: prestashop
  db_user:
    type: string
    label: MariaDB script user
    default: prestashop
  db_password:
    type: string
    label: MariaDB script user's password
    default: prestashop1234


resources:
  instance_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: network }
      security_groups:
        - { get_param: sg }

  instance:
    type: OS::Nova::Server
    properties:
      name: db
      key_name: { get_param: key_name }
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      networks:
        - network: { get_param: network }
        - port: { get_resource: instance_port }
      user_data:
        str_replace:
          template: { get_file : db_bootstrap.sh }
          params:
            $MYSQL_ROOT_PASSWORD: { get_param: db_root_password }
            $MYSQL_DATABASE: { get_param: db_name }
            $MYSQL_USER: { get_param: db_user }
            $MYSQL_PASSWORD: { get_param: db_password }

outputs:
  instance_ip:
    description: IP address of the deployed instance
    value: { get_attr: [instance, first_address] }
